### ISSUE TITLE
SDK Manual - add documentation

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/info_sdk#316] opened 2021-02-22 10:29 UTC
tfgrid sdk documentation

- how to install
- how to get started
- copy info from jsng - jssdk
- needs to be on sdk.threefold.io

**Comment by xmonader** [comment] 2021-02-23 15:49
duplicate of https://github.com/threefoldfoundation/info_sdk/issues/319

**Closed by xmonader** 2021-02-23 15:49 UTC
